const PDFDocument = require('pdfkit');

/**
 * PDF Generator Service - Professional document request report generation
 *
 * Features:
 * - Professional PDF layout with headers, footers, and branding
 * - Automatic page breaks and table pagination
 * - Dynamic title generation based on user role
 * - Summary statistics section
 * - Tabular data display for document requests
 * - Date range display
 * - Generation metadata (generated by, generated at)
 *
 * Design:
 * - San Pablo Colleges official branding
 * - Registrar's Office designation
 * - Professional typography and spacing
 * - Clean table formatting
 * - ISO date formatting
 */
class PDFGenerator {
    /**
     * Configuration for PDF generation
     */
    constructor() {
        this.pageWidth = 595; // A4 width in points
        this.pageHeight = 842; // A4 height in points
        this.margin = 40;
        this.lineHeight = 15;
        this.smallLineHeight = 12;
        this.tableFontSize = 8;
        this.tableRowHeight = 18;
    }

    /**
     * Generate professional document request report PDF
     *
     * @param {Object} options - Report options
     * @param {string} options.title - Report title
     * @param {string} options.userRole - Role of report generator (admin or staff)
     * @param {string} options.departmentName - Department name for the report
     * @param {Object} options.dateRange - Date range { from: 'YYYY-MM-DD', to: 'YYYY-MM-DD' }
     * @param {Object} options.statistics - Summary statistics
     * @param {Array} options.data - Array of document requests
     * @param {string} options.generatedBy - Email of user who generated report
     * @param {Date} options.generatedAt - Timestamp of generation
     * @returns {Promise<Buffer>} PDF file buffer
     */
    generateReportPDF = async (options) => {
        return new Promise((resolve, reject) => {
            try {
                const {
                    title,
                    userRole,
                    departmentName,
                    dateRange,
                    statistics,
                    data,
                    generatedBy,
                    generatedAt
                } = options;

                // Create PDF document
                const doc = new PDFDocument({
                    size: 'A4',
                    margin: this.margin,
                    bufferPages: true
                });

                // Collect PDF data
                const chunks = [];
                doc.on('data', chunk => chunks.push(chunk));
                doc.on('end', () => {
                    const pdfBuffer = Buffer.concat(chunks);
                    resolve(pdfBuffer);
                });
                doc.on('error', reject);

                // =============== PAGE 1 HEADER ===============
                this.drawHeader(doc);

                // =============== MAIN TITLE ===============
                doc.fontSize(16).font('Helvetica-Bold');
                doc.text(title, { align: 'center', underline: true });
                doc.moveDown(0.5);

                // =============== DATE RANGE ===============
                doc.fontSize(10).font('Helvetica');
                const fromDateObj = new Date(dateRange.from);
                const toDateObj = new Date(dateRange.to);
                const formattedFrom = this.formatDate(fromDateObj);
                const formattedTo = this.formatDate(toDateObj);

                doc.text(`Report Period: ${formattedFrom} to ${formattedTo}`, {
                    align: 'center',
                    fontSize: 10
                });
                doc.moveDown(0.8);

                // =============== SUMMARY STATISTICS SECTION ===============
                this.drawStatisticsSection(doc, statistics);
                doc.moveDown(0.8);

                // =============== TABLE HEADER ===============
                const tableTop = doc.y;
                const tableColumns = [
                    { key: 'studentId', label: 'Student ID', width: 70 },
                    { key: 'studentName', label: 'Student Name', width: 100 },
                    { key: 'course', label: 'Course', width: 80 },
                    { key: 'documentType', label: 'Document Type', width: 85 },
                    { key: 'dateRequested', label: 'Date Requested', width: 70 },
                    { key: 'status', label: 'Status', width: 60 }
                ];

                // Draw table header
                this.drawTableHeader(doc, tableColumns);

                // =============== TABLE ROWS WITH PAGE BREAKS ===============
                let currentY = doc.y;
                const contentHeight = this.pageHeight - this.margin * 2;
                const headerFooterHeight = 120; // Approximate height reserved for header/footer

                for (let i = 0; i < data.length; i++) {
                    const row = data[i];

                    // Check if we need a page break
                    if (currentY + this.tableRowHeight > this.pageHeight - this.margin - 60) {
                        // Add footer to current page
                        this.drawPageFooter(doc, generatedBy, generatedAt);

                        // Start new page
                        doc.addPage();

                        // Add header to new page
                        this.drawHeader(doc);
                        doc.moveDown(1.5);

                        // Redraw table header on new page
                        this.drawTableHeader(doc, tableColumns);
                        currentY = doc.y;
                    }

                    // Draw table row
                    this.drawTableRow(doc, row, tableColumns);
                    currentY = doc.y;
                }

                // =============== FINAL PAGE FOOTER ===============
                this.drawPageFooter(doc, generatedBy, generatedAt);

                // =============== CLOSE DOCUMENT ===============
                doc.end();

            } catch (error) {
                reject(error);
            }
        });
    };

    /**
     * Draw PDF header with institution branding
     * @param {PDFDocument} doc - PDFKit document
     */
    drawHeader = (doc) => {
        const headerY = doc.y;

        // Institution name and office designation
        doc.fontSize(14).font('Helvetica-Bold');
        doc.text('SAN PABLO COLLEGES', { align: 'center' });

        doc.fontSize(11).font('Helvetica');
        doc.text("Registrar's Office", { align: 'center' });

        doc.fontSize(9).font('Helvetica-Oblique');
        doc.text('Laguna Province, Philippines', { align: 'center' });

        doc.moveDown(0.5);

        // Horizontal line separator
        const lineY = doc.y;
        doc.strokeColor('#000000');
        doc.lineWidth(1);
        doc.moveTo(this.margin, lineY)
            .lineTo(this.pageWidth - this.margin, lineY)
            .stroke();

        doc.moveDown(0.5);
    };

    /**
     * Draw statistics summary section
     * @param {PDFDocument} doc - PDFKit document
     * @param {Object} stats - Statistics object
     */
    drawStatisticsSection = (doc, stats) => {
        doc.fontSize(11).font('Helvetica-Bold');
        doc.text('SUMMARY STATISTICS', { underline: true });
        doc.moveDown(0.3);

        doc.fontSize(9).font('Helvetica');

        // Create a simple two-column layout for stats
        const statItems = [
            { label: 'Total Requests', value: stats.total },
            { label: 'Pending', value: stats.pending },
            { label: 'Processing', value: stats.processing },
            { label: 'Approved', value: stats.approved },
            { label: 'Released', value: stats.released },
            { label: 'Declined', value: stats.declined }
        ];

        const col1X = this.margin;
        const col2X = this.pageWidth / 2;
        let statIndex = 0;
        let y = doc.y;

        for (let i = 0; i < Math.ceil(statItems.length / 2); i++) {
            // First column
            if (statIndex < statItems.length) {
                const stat = statItems[statIndex];
                doc.text(
                    `${stat.label}: ${stat.value}`,
                    col1X,
                    y,
                    { width: col2X - col1X - 10 }
                );
                statIndex++;
            }

            // Second column
            if (statIndex < statItems.length) {
                const stat = statItems[statIndex];
                doc.text(
                    `${stat.label}: ${stat.value}`,
                    col2X,
                    y,
                    { width: col2X - 10 }
                );
                statIndex++;
            }

            y += this.smallLineHeight + 3;
        }

        doc.y = y;
    };

    /**
     * Draw table header row
     * @param {PDFDocument} doc - PDFKit document
     * @param {Array} columns - Column definitions
     */
    drawTableHeader = (doc, columns) => {
        const headerY = doc.y;
        const headerRowHeight = 25;

        // Background for header
        doc.rect(this.margin, headerY, this.pageWidth - this.margin * 2, headerRowHeight)
            .fillAndStroke('#2c3e50', '#000000');

        // Header text
        doc.fillColor('#ffffff').fontSize(this.tableFontSize).font('Helvetica-Bold');

        let x = this.margin + 5;
        for (const col of columns) {
            doc.text(col.label, x, headerY + 5, {
                width: col.width - 10,
                height: headerRowHeight - 10,
                align: 'left',
                valign: 'center'
            });
            x += col.width;
        }

        // Reset color for content
        doc.fillColor('#000000');
        doc.moveDown(2);
    };

    /**
     * Draw a single table row
     * @param {PDFDocument} doc - PDFKit document
     * @param {Object} row - Row data
     * @param {Array} columns - Column definitions
     */
    drawTableRow = (doc, row, columns) => {
        const rowY = doc.y;
        const rowHeight = this.tableRowHeight;

        // Alternate row colors for readability
        const isEvenRow = Math.floor((rowY - this.margin) / rowHeight) % 2 === 0;
        if (isEvenRow) {
            doc.rect(this.margin, rowY, this.pageWidth - this.margin * 2, rowHeight)
                .fill('#f8f9fa');
        }

        // Border
        doc.strokeColor('#cccccc').lineWidth(0.5);
        doc.rect(this.margin, rowY, this.pageWidth - this.margin * 2, rowHeight)
            .stroke();

        // Row text
        doc.fillColor('#000000').fontSize(this.tableFontSize).font('Helvetica');

        let x = this.margin + 5;
        for (const col of columns) {
            let cellValue = row[col.key];

            // Format values
            if (col.key === 'dateRequested' && cellValue) {
                const dateObj = new Date(cellValue);
                cellValue = this.formatDate(dateObj);
            }

            // Truncate long text
            if (cellValue && cellValue.length > 25) {
                cellValue = cellValue.substring(0, 22) + '...';
            }

            doc.text(cellValue || 'N/A', x, rowY + 3, {
                width: col.width - 10,
                height: rowHeight - 6,
                align: 'left',
                valign: 'center'
            });

            x += col.width;
        }

        doc.moveDown(1.2);
    };

    /**
     * Draw page footer with metadata
     * @param {PDFDocument} doc - PDFKit document
     * @param {string} generatedBy - Email of report generator
     * @param {Date} generatedAt - Generation timestamp
     */
    drawPageFooter = (doc, generatedBy, generatedAt) => {
        const footerY = this.pageHeight - this.margin - 40;

        // Horizontal line separator
        doc.strokeColor('#cccccc').lineWidth(0.5);
        doc.moveTo(this.margin, footerY)
            .lineTo(this.pageWidth - this.margin, footerY)
            .stroke();

        // Footer text
        doc.fontSize(7).font('Helvetica').fillColor('#666666');
        const pageCount = doc.bufferedPageRange().count;
        const currentPage = doc.bufferedPageRange().count;

        const footerText = `Generated by: ${generatedBy} | Generated: ${this.formatDateTime(
            generatedAt
        )} | Page ${currentPage} of ${pageCount}`;

        doc.text(footerText, this.margin, footerY + 5, {
            width: this.pageWidth - this.margin * 2,
            align: 'center',
            fontSize: 7
        });

        // Reset color
        doc.fillColor('#000000');
    };

    /**
     * Format date to readable format (MM/DD/YYYY)
     * @param {Date} date - Date object
     * @returns {string} Formatted date
     */
    formatDate = (date) => {
        if (!date || isNaN(date.getTime())) {
            return 'N/A';
        }
        const month = String(date.getMonth() + 1).padStart(2, '0');
        const day = String(date.getDate()).padStart(2, '0');
        const year = date.getFullYear();
        return `${month}/${day}/${year}`;
    };

    /**
     * Format date and time (MM/DD/YYYY HH:MM AM/PM)
     * @param {Date} date - Date object
     * @returns {string} Formatted date and time
     */
    formatDateTime = (date) => {
        if (!date || isNaN(date.getTime())) {
            return 'N/A';
        }

        const months = [
            'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
            'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
        ];

        const month = months[date.getMonth()];
        const day = String(date.getDate()).padStart(2, '0');
        const year = date.getFullYear();
        let hours = date.getHours();
        const minutes = String(date.getMinutes()).padStart(2, '0');
        const ampm = hours >= 12 ? 'PM' : 'AM';
        hours = hours % 12;
        hours = hours ? hours : 12;

        return `${month} ${day}, ${year} ${hours}:${minutes} ${ampm}`;
    };
}

module.exports = PDFGenerator;
